project:
  type: book
  output-dir: docs

book:
  title: "Learning Linux Notes"
  author: "Lingyun Zhang"
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - ch1.qmd
    - ch2.qmd
    - commands.qmd


format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



